### ISSUE TITLE
Build instructions for Fedora/Redhat

### ISSUE THREAD

**Issue by KarlLevik** [terminusdb/terminus-server#28] opened 2019-10-06 12:53 UTC
`BUILD.md` has instructions for Debian, but not Fedora.

So for fun I tried building on Fedora release 30 (Thirty), but no luck. I did this (as root): 

```
dnf install pl
swipl
pack_install('https://github.com/GavinMendelGleason/hdt.git').
```

> Create directory for packages
>    (1) * /root/lib/swipl/pack
>    (2)   /usr/lib64/swipl-8.0.3/pack
>    (3)   Cancel
> 
> Your choice?
> 
> % Cloning into '/usr/lib64/swipl-8.0.3/pack/hdt'...
> Verify package status (anonymously)
> 	at "https://www.swi-prolog.org/pack/query" Y/n? 
> % Contacting server at https://www.swi-prolog.org/pack/query ...
> ERROR: Server reported the following error:
> ERROR: No permission to register pack(hdt) `'https://github.com/GavinMendelGleason/hdt.git''
> Package:                hdt
> Title:                  Access RDF HDT files
> Installed version:      0.5
> Author:                 Jan Wielemaker <J.Wielemaker@vu.nl>
> Maintainer:             Jan Wielemaker <J.Wielemaker@vu.nl>
> Packager:               Jan Wielemaker <J.Wielemaker@vu.nl>
> Home page:              https://github.com/GavinMendelGleason/hdt
> Download URL:           https://github.com/GavinMendelGleason/hdt.git
> Run post installation scripts for pack "hdt" Y/n? 
> % git submodule update --init
> % Submodule 'hdt-cpp' (https://github.com/rdfhdt/hdt-cpp.git) registered for path 'hdt-cpp'
> % Cloning into '/usr/lib64/swipl-8.0.3/pack/hdt/hdt-cpp'...
> % Submodule path 'hdt-cpp': checked out 'a8aafe32e0209a50a7671ddd5376b5c0d6934496'
> % cd hdt-cpp && ./autogen.sh
> % aclocal: installing 'm4/pkg.m4' from '/usr/share/aclocal/pkg.m4'
> % configure.ac:16: installing 'build/ar-lib'
> % configure.ac:12: installing 'build/compile'
> % configure.ac:5: installing 'build/install-sh'
> % configure.ac:5: installing 'build/missing'
> ERROR: libcds/Makefile.am:8: error: Libtool library used but 'LIBTOOL' is undefined
> ERROR: libcds/Makefile.am:8:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
> ERROR: libcds/Makefile.am:8:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
> ERROR: libcds/Makefile.am:8:   If 'LT_INIT' is in 'configure.ac', make sure
> ERROR: libcds/Makefile.am:8:   its definition is in aclocal's search path.
> % libcds/Makefile.am: installing 'build/depcomp'
> % parallel-tests: installing 'build/test-driver'
> ERROR: libhdt/Makefile.am:23: error: Libtool library used but 'LIBTOOL' is undefined
> ERROR: libhdt/Makefile.am:23:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
> ERROR: libhdt/Makefile.am:23:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
> ERROR: libhdt/Makefile.am:23:   If 'LT_INIT' is in 'configure.ac', make sure
> ERROR: libhdt/Makefile.am:23:   its definition is in aclocal's search path.
> % autoreconf: automake failed with exit status: 1
> % make: *** [Makefile:23: hdt-cpp/libhdt/.make-senitel] Error 1
> ERROR: Process "process(path(make),[all])": exit status: 2
> ERROR: In:
> ERROR:   [18] throw(error(process_error(...,...),_28682))
> ERROR:   [16] '$apply':forall(prolog_pack:member(all,...),prolog_pack:run_process(...,...,...)) at /usr/lib64/swipl-8.0.3/boot/apply.pl:52
> ERROR:   [12] prolog_pack:pack_post_install(hdt,'/usr/lib64/swipl-8.0.3/pack/hdt',[git(true),...|...]) at /usr/lib64/swipl-8.0.3/library/prolog_pack.pl:1017
> ERROR:    [7] <user>
> ERROR: 
> ERROR: Note: some frames are missing due to last-call optimization.
> ERROR: Re-run your program in debug mode (:- debug.) to get more detail.
>

**Comment by rrooij** [comment] 2019-10-06 13:09
Did you install hdt-cpp and its requirements?

See: https://github.com/rdfhdt/hdt-cpp#prerequisites

**Comment by KarlLevik** [comment] 2019-10-06 16:40
Ah, I didn't do that - I just followed the order of the instructions in the `BUILD.md` file, and the HDT library is next. OK, so I've now installed that. `pack_install('https://github.com/GavinMendelGleason/hdt.git').` now gets much further, but stops after a while with this error:

> % gcc  -fPIC -pthread -I"/usr/lib64/swipl-8.0.3/include" -Ihdt-cpp/libhdt/include -g -c -o c/hdt4pl.o c/hdt4pl.cpp
> ERROR: c/hdt4pl.cpp:36:10: fatal error: SWI-Stream.h: No such file or directory
> ERROR:    36 | #include <SWI-Stream.h>
> ERROR:       |          ^~~~~~~~~~~~~~
> ERROR: compilation terminated.

**Comment by GavinMendelGleason** [comment] 2019-10-06 16:52
Oh dear! Both good things for us to know! I'll have to edit the README.md to reflect this.

I'd imagine the problem is caused by needing header files for swi-prolog. If there is a dev package you can install for RedHat, that will probably fix it. Otherwise you'll have to get the swipl source: https://github.com/SWI-Prolog/swipl

Easiest way to get the correct location for header files is probably to build and install swipl unfortunately.

We are actively moving the back-end storage to our own terminus-store which should simplify the entire build process significantly.

**Comment by rrooij** [comment] 2019-10-06 17:43
@KarlLevik You probably need to install `pl-devel` as well.

https://apps.fedoraproject.org/packages/pl-devel

And indeed as Gavin said, we hope to make the process a lot easier by moving to our own storage backend written in Rust.

**Comment by KarlLevik** [comment] 2019-10-06 20:56
Yes, it seems `dnf install pl-devel` does the trick!

I've run into some other issues, but that's probably for another ticket.

**Comment by rrooij** [comment] 2019-10-07 08:12
I have added Fedora instructions in the dev branch:

https://github.com/terminusdb/terminus-server/blob/dev/BUILD.md#fedora-or-red-hat

Do you think they are sufficient @KarlLevik ?

**Closed** 2019-10-08 10:07 UTC
